version: 0.2

env:
  variables:
    artifact_s3_bucket: "value"

phases:
  install:
    commands:
      - chmod +x build.sh
  build:
    commands:
      - echo Run unit test
      - ./build.sh
  post_build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket ${artifact_s3_bucket} --output-template-file packaged.yaml
artifacts:
  type: zip
  files:
    - packaged.yaml
